package vn.vistark.pharmass.core.constants

class RequestCode {
    companion object {
        val REQUEST_INVENTORY_LIMIT_OPTIONS_PICKER_CODE = 4585
        val REQUEST_INVENTORY_LIMIT_RELOAD_CODE = 4584
        val REQUEST_GOODS_CATEGORY_RELOAD_CODE = 4583
        val REQUEST_SUPPLIER_CREATE_CODE = 4582
        val REQUEST_SUPPLIER_UPDATE_CODE = 4581
        val REQUEST_GOODS_CREATE_CODE = 4580
        val REQUEST_GOODS_UPDATE_CODE = 4579
        val REQUEST_PHARMACY_OPTION_PICKER_CODE = 4578
        val REQUEST_TIME_RANGE_PICKER_CODE = 4577
        val REQUEST_BILL_ITEM_DETAILS_CODE = 4576
        val REQUEST_GOODS_PICKER_CODE = 4575
        val REQUEST_USER_PICKER_CODE = 4574
        val REQUEST_SUPPLIER_PICKER_CODE = 4573
        val PERMISSION_REQUEST_ALL = 4572
        val REQUEST_BARCODE_SCANNER = 4571
        val REQUEST_PICK_PHOTO = 4570
        val REQUEST_TAKE_PHOTO = 4569
        val PICK_AVATAR = 1234
        val REQUEST_ADDRESS_CODE = 4567
        val REQUEST_MEDICINE_CATEGORY_CODE = 4568
        val PICK_LOGO = 1221
        val PICK_FEATURE_IMAGE = 1222
    }
}